language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11
    - os: linux
      dist: bionic
      addons:
        apt:
          packages: [ 'libstdc++-5-dev' ]

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
